version: '3'
services:

  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - /server/
    command: python3 server.py
  
  app:
    build: ./app
    expose:
      - ${REACT_APP_PORT}
    environment:
      - REACT_APP_PORT = ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - /app/
      - /app/src/
      - /app/public/
    links:
      - server
    command: npm run start

